[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "arquivisionpy"
version = "0.1.0"
description = "Librería en Python para detección de líneas, esquinas e intersecciones en planos arquitectónicos"
authors = [
    { name = "Rodrigo Quezada" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "opencv-python",
    "numpy",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["."]